## **Задание на повторение материала


In [3]:
import numpy as np
import pandas as pd

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [51]:
a = np.linspace(12, 24, 12, endpoint = False)
a

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [38]:
a1 = a.reshape(3, 4)
a1

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [12]:
a2 = a.reshape(4, 3)
a2

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [16]:
a3 = a.reshape(3, 4, order='F')
a3

array([[12., 15., 18., 21.],
       [13., 16., 19., 22.],
       [14., 17., 20., 23.]])

In [19]:
a4 = a.reshape(6, 2)
a4

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [21]:
a5 = a.reshape(2, 6, order='F')
a5

array([[12., 14., 16., 18., 20., 22.],
       [13., 15., 17., 19., 21., 23.]])

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [23]:
a1 = a.reshape(-1, 4)
a1

array([[12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.]])

In [24]:
a2 = a.reshape(-1, 3)
a2

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [25]:
a3 = a.reshape(-1, 2)
a3

array([[12., 13.],
       [14., 15.],
       [16., 17.],
       [18., 19.],
       [20., 21.],
       [22., 23.]])

In [26]:
a4 = a.reshape(4, -1)
a4

array([[12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [52]:
a5 = a.reshape(1, -1)
a5

array([[12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.]])

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?


Одномерный массив содержит элементы только в одном измерении. 
Если есть столбец и строки - это уже два измерения. Значи, массив двумерный.

5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой 
из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [47]:
ab = np.random.randn(3, 4)

print(ab)

[[-0.06203839  0.87827866  0.30225609  0.36956511]
 [ 0.93707297 -2.43750875  0.02644626 -1.62054997]
 [-0.37220232  1.05363998  0.13716661 -1.77931932]]


In [48]:
ab1 = ab.reshape(1, -1)
ab1

array([[-0.06203839,  0.87827866,  0.30225609,  0.36956511,  0.93707297,
        -2.43750875,  0.02644626, -1.62054997, -0.37220232,  1.05363998,
         0.13716661, -1.77931932]])

In [71]:
ab1.size

12

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [58]:
a = np.linspace(20, 0, 2, endpoint = False)

print(a)

[20. 10.]


7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?


In [70]:
b = np.linspace(20, 1, 10, endpoint = False, retstep = 2)

print(b)

(array([20. , 18.1, 16.2, 14.3, 12.4, 10.5,  8.6,  6.7,  4.8,  2.9]), -1.9)


8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.


In [88]:
a = np.zeros((2, 2))

print(a)

[[0. 0.]
 [0. 0.]]


In [77]:
b = np.ones((3, 2))

print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [89]:
v = np.concatenate((a,b), axis=0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [90]:
v.size

10

9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. 
Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. 
Получить матрицу At путем транспонирования матрицы A. 
Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. К
акой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [8]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [11]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [103]:
d = np.linalg.det(B)

print(d)
# определитель матрицы равен 0, значит посчитать обратную матрицы нельзя.
# обратную матрицу можно посчитать только для матрицы, определитель которой не равен 0.

0.0


10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [108]:
np.random.seed(42)

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [17]:
C = np.linspace(0, 16, 16, endpoint = False)

print(c)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]


12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [18]:
C = C.reshape(-1, 4)
C

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])

In [29]:
D = (B + C * 10)
D

array([[  5.,  24.,  43.,  62.],
       [ 54., 100., 146., 192.],
       [103., 176., 249., 322.],
       [152., 252., 352., 452.]])

In [30]:
r = np.linalg.matrix_rank(D)
print ("Ранг матрицы:", r)

Ранг матрицы: 2


In [32]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 4.66062690e+13, -1.49229688e+13, -1.09972869e+14,
         7.82895692e+13],
       [ 1.63480451e+14, -3.81454387e+14,  2.72467419e+14,
        -5.44934838e+13],
       [-4.66779710e+14,  8.07677680e+14, -2.15016230e+14,
        -1.25881740e+14],
       [ 2.56692989e+14, -4.11300324e+14,  5.25216801e+13,
         1.02085655e+14]])

13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [34]:
D_inv[D_inv<0] = 0
D_inv[D_inv>0] = 1

  
# результат печати

print(D_inv) 

[[1. 0. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 1. 1.]]
